module.exports = {
    apps: [
        {
            name: 'auth',
            script: 'dist/apps/auth/main.js',
            instances: 1,
            autorestart: true,
            watch: false,
            node_args: '--experimental-specifier-resolution=node',
            env_file: '.env',
        },
        {
            name: 'trainer-bc',
            script: 'dist/apps/trainer-bc/main.js',
            instances: 1,
            autorestart: true,
            watch: false,
            node_args: '--experimental-specifier-resolution=node',
            env_file: '.env',
        },
        {
            name: 'trainee-bc',
            script: 'dist/apps/trainee-bc/main.js',
            instances: 1,
            autorestart: true,
            watch: false,
            node_args: '--experimental-specifier-resolution=node',
            env_file: '.env',
        },
        {
            name: 'package-bc',
            script: 'dist/apps/package-bc/main.js',
            instances: 1,
            autorestart: true,
            watch: false,
            node_args: '--experimental-specifier-resolution=node',
            env_file: '.env',
        },
        {
            name: 'appointment-bc',
            script: 'dist/apps/appointment-bc/main.js',
            instances: 1,
            autorestart: true,
            watch: false,
            node_args: '--experimental-specifier-resolution=node',
            env_file: '.env',
        },
    ],
};
